"use strict";
exports.__esModule = true;
var main_1 = require("./main");
var movies_1 = require("./movies");
var pelicula1 = new movies_1.Movie("El castigador", 2001, "North American", "Action");
pelicula1.actors = [main_1.actor1, main_1.actor2];
pelicula1.director = main_1.director1;
pelicula1.writer = "John Ashley";
pelicula1.language = "English";
pelicula1.platform = "Netflix";
pelicula1.isMCU = false;
pelicula1.mainCharacterName = "Joshua Perkins";
pelicula1.producer = [main_1.producer1, main_1.producer2];
pelicula1.distributor = "Sony";
pelicula1.filmsDetails();
console.log("---------------------------------------------------------------------------------");
var pelicula2 = new movies_1.Movie("Spiderman - Far from Codenotch", 2021, "Spanish", "Action");
pelicula2.actors = [main_1.actor3, main_1.actor5];
pelicula2.director = main_1.director2;
pelicula2.writer = "Michael Tobbs";
pelicula2.language = "Spanish";
pelicula2.platform = "Disney";
pelicula2.isMCU = true;
pelicula2.mainCharacterName = "Peter Parker";
pelicula2.producer = [main_1.producer4, main_1.producer9];
pelicula2.distributor = "Marvel";
pelicula2.filmsDetails();
console.log("---------------------------------------------------------------------------------");
var pelicula3 = new movies_1.Movie("Escape Total", 1990, "British", "Comedy-action");
pelicula3.actors = [main_1.actor8, main_1.actor9];
pelicula3.director = main_1.director5;
pelicula3.writer = "Daniel Oswall";
pelicula3.language = "English";
pelicula3.platform = "Amazon video";
pelicula3.isMCU = false;
pelicula3.mainCharacterName = "Francis Johnson";
pelicula3.producer = [main_1.producer6, main_1.producer8];
pelicula3.distributor = "Amazon";
pelicula3.filmsDetails();
